studentId: "*"
password: "*"

message:

  tw: 1
  sfzx: 1
  area: "陕西省 西安市 雁塔区"
  city: "西安市"
  province: "陕西省"
  address: "陕西省西安市雁塔区电子城街道西安电子科技大学北校区世纪广场"
  geo_api_info: "{\"type\":\"complete\",\"position\":{\"Q\":34.230770128039,\"R\":108.91731526692797,\"lng\":108.917315,\"lat\":34.23077},\"location_type\":\"html5\",\"message\":\"Get ipLocation failed.Get geolocation success.Convert Success.Get address success.\",\"accuracy\":57,\"isConverted\":true,\"status\":1,\"addressComponent\":{\"citycode\":\"029\",\"adcode\":\"610113\",\"businessAreas\":[],\"neighborhoodType\":\"\",\"neighborhood\":\"\",\"building\":\"\",\"buildingType\":\"\",\"street\":\"太白南路\",\"streetNumber\":\"2号\",\"country\":\"中国\",\"province\":\"陕西省\",\"city\":\"西安市\",\"district\":\"雁塔区\",\"township\":\"电子城街道\"},\"formattedAddress\":\"陕西省西安市雁塔区电子城街道西安电子科技大学北校区世纪广场\",\"roads\":[],\"crosses\":[],\"pois\":[],\"info\":\"SUCCESS\"}"
  sfcyglq: 0
  sfyzz: 0
  qtqk: "无"
  ymtys: 0
